
services:
#======================Mariadb=====================
  mariadb:
    image: mariadb:mohimi
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - myserv
    restart: on-failure
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      interval: 1s
      timeout: 5s
      retries: 10
  #========================= Nginx=====================

  nginx:
    container_name: nginx
    image: nginx:mohimi
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - myserv
    restart: on-failure
  #=========================== Wordpress ===============

  wordpress:
    image: wordpress:mohimi
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb :
        condition: service_healthy

    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - myserv
    restart: on-failure

#================= adminer =============================

  adminer:
    image: adminer:mohimi
    container_name: adminer
    build:
      ./requirements/bonus/adminer
    env_file:
      - .env
    depends_on:
      - mariadb
    ports:
      - "7070:8080"
    networks:
      - myserv
    restart: on-failure

#=================== redis ============================

  redis:
    image: redis:mohimi
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - "6979:6979"
    networks:
      - myserv
    restart: on-failure
#================== myweb ==============================

  myweb:
    image: myweb:mohimi
    container_name: myweb
    build:
      ./requirements/bonus/myweb
    ports:
      - "7000:7000"
    networks:
      - myserv
    restart: on-failure
#=================== ftp ===============================

  ftp:
    container_name: ftp
    image: ftp:mohimi
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
      - "4000-4100:4000-4100"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - myserv
    restart: on-failure
#=================== service ==========================

  # # Portainer Service (Docker Management Tool)
  # service:
  #   image: service:mohimi
  #   container_name: mohimi
  #   build:
  #     context: ./requirements/bonus/service
  #   ports:
  #     - "6000:6000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - myserv
  #   restart: on-failure

#=================== volumes ===========================

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/mohimi/data/mariadb
      type: none
      o: bind

  wordpress:
    driver: local
    driver_opts:
      device: /home/mohimi/data/wordpress
      type: none
      o: bind
#================ Networks =====================
networks:
  myserv:
    name: myserv